amazon_dev:
  service: S3
  access_key_id: <%= ENV['s3_access_key_id'] %>
  secret_access_key: <%= ENV['s3_secret_access_key'] %>
  region: "us-east-2"
  bucket: "phasebook-pro"

amazon_pro:
  service: S3
  access_key_id: <%= ENV['s3_access_key_id'] %>
  secret_access_key: <%= ENV['s3_secret_access_key'] %>
  region: "us-east-2"
  bucket: "phasebook-pro"
